### ISSUE TITLE
Is it possible to add a parameter to pass in a specified Basilisk download url?

### ISSUE THREAD

**Issue by kekxv** [bazelbuild/setup-bazelisk#120]
hi. Now `gitea` supports `actions` similar to `GitHub Actions`, but it does `not support` `gitHub.token`. Is it possible to add a parameter to pass in a specified Basilisk download url?
（现在gitea支持类似github actions 的actions，但是他不支持github.token，所以可以增加参数，传入指定的basilisk下载路径吗？）

**Comment by junyer** [comment]
Closing this issue because this repository is about to be archived.
