### ISSUE TITLE
Documentation on how to support incremental builds?

### ISSUE THREAD

**Issue by kaihendry** [bazelbuild/setup-bazelisk#6]
Github Actions forum pointed me here https://github.community/t/speeding-up-deployments/139003/3?u=kaihendry I think, in order to achieve incremental builds.

Basically I'm looking for a solution where my build is cached and I am wondering if this is the solution. Currently nothing in the README suggests it will be!

**Comment by mishas** [comment]
@kaihendry,
This action is just to help you setup the binary that will run Bazel inside the github action.
If you want to have incremental builds, you'll need to utilize the cache actions (https://github.com/marketplace/actions/cache) to cache the Bazel cache for future builds.
Please note that it is shown in the example as the `# Optional` step.

If you want to better understand how Bazel works and how it helps you cache ting, you should read on Bazel itself (https://bazel.build).
