### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/setup-bazelisk#91]
It'd be cool to get a new release! There's been a lot of nice dependabot upgrades since the last release a year ago.

**Comment by loopingz** [comment]
I forked and publish it on `loopingz/setup-bazelisk@v3` as I needed the multi arch support

I can PR back to the repo if someone can merge

**Comment by loopingz** [comment]
Yes, I think using @main should work.

It might be worth mentioning in the doc that to use the multi-arch feature, we need to use `@main`.
But overall, if you lost the ability to release, I think having a fork for releasing and maintaining seems more logical.

Thanks for the work done already

**Comment by junyer** [comment]
Closing this issue because this repository is about to be archived.
